### ISSUE TITLE
Create `wrap_err` function that mimics the behaviour of `Either.wrap`

### ISSUE THREAD

**Issue by neslinesli93** [sphaso/noether#15]
Same behaviour, but wraps errors in `{:error, _}` tuples if they are not already

**Comment by sphaso** [comment]
Just to make sure, would this be a valid behavior for `wrap_err`?

```
iex> wrap_err({:ok, 1})
{:error, 1}
```

**Comment by neslinesli93** [comment]
As you can see from the [documentation of wrap/1](https://github.com/sphaso/noether/blob/master/lib/noether/either.ex#L101), if it's already an ok/error tuple, it's returned as is. I think the behaviour of `wrap_err/1` should be the same!

**Comment by sphaso** [comment]
@neslinesli93 makes sense, thanks!

**Comment by pablocostass** [comment]
Should I commit also an `unwrap_err` function following the same trend?

**Comment by sphaso** [comment]
@pablocostass there's no need for that right now, thank you!
