### ISSUE TITLE
What about adding Noether.List.wrap?

### ISSUE THREAD

**Issue by cottinisimone** [sphaso/noether#33]
Could be something like this:

```
iex> Noether.List.wrap(nil)
[]

iex> Noether.List.wrap(1)
[1]

iex> Noether.List.wrap([1])
[[1]]
```

**Comment by sphaso** [comment]
There is List.wrap in the standard library. The only difference I see is that it keeps lists as-is when passed as input.
Do you often find the need to wrap lists?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by cottinisimone** [comment]
Ops. Good point
