### ISSUE TITLE
Implement flat_map

### ISSUE THREAD

**Issue by cottinisimone** [sphaso/noether#8]
either module could have a `flat_map` and `flatten` to flat nested oks (right value mapped)

Moreover could be useful to implement a `map_ok` and `map_error` functions

**Comment by sphaso** [comment]
I like the idea of `flatten`, thanks!      
What's your idea for `flat_map`? is it `bind` + `map` or `flatten` + `Enum.map`?      
Could you also give some examples for `map_ok` and `map_error`?     

Feel free to open a PR, or we could add you as a collaborator if you prefer.

**Comment by sphaso** [comment]
Fixed by #10
